language: scala
scala:
   - 2.10.4
   - 2.11.4
branches:
  only:
    - master
    - com.sandinh
before_script:
   - cd module-code/
script:
   - sbt ++$TRAVIS_SCALA_VERSION compile
   - sbt ++$TRAVIS_SCALA_VERSION test
jdk:
   - oraclejdk7
   - oraclejdk8
